const adminsData = [
    {
        id: 1,
        name: "User 1",
        contact: "0000000000",
        email: "User@gmail.com",
        role: "Manager",
        status: "Active",
    },
    {
        id: 2,
        name: "User 1",
        contact: "0000000000",
        email: "User@gmail.com",
        role: "Manager",
        status: "Inactive",
    },
    {
        id: 3,
        name: "User 1",
        contact: "0000000000",
        email: "User@gmail.com",
        role: "Manager",
        status: "Active",
    },
    {
        id: 4,
        name: "User 1",
        contact: "0000000000",
        email: "User@gmail.com",
        role: "Manager",
        status: "Inactive",
    },
    {
        id: 5,
        name: "User 1",
        contact: "0000000000",
        email: "User@gmail.com",
        role: "Manager",
        status: "Active",
    },
    {
        id: 6,
        name: "User 1",
        contact: "0000000000",
        email: "User@gmail.com",
        role: "Manager",
        status: "Inactive",
    },
    {
        id: 7,
        name: "User 1",
        contact: "0000000000",
        email: "User@gmail.com",
        role: "Manager",
        status: "Active",
    },
    {
        id: 8,
        name: "User 1",
        contact: "0000000000",
        email: "User@gmail.com",
        role: "Manager",
        status: "Inactive",
    },
];

export default adminsData;